#!/bin/bash

echo "🚀 マイグレーション実行ガイド"
echo "============================"
echo ""
echo "以下のコマンドをターミナルで実行してください："
echo ""
echo "1. Supabaseダッシュボードでデータベースパスワードを確認:"
echo "   https://supabase.com/dashboard/project/vyddhllzjjpqxbouqivf/settings/database"
echo ""
echo "2. 以下のコマンドを実行してパスワードを入力:"
echo "   supabase db push --password [your-database-password]"
echo ""
echo "または、環境変数として設定:"
echo "   export SUPABASE_DB_PASSWORD=[your-database-password]"
echo "   supabase db push"
echo ""
echo "============================"
echo ""
echo "代替方法: Supabaseダッシュボードで直接実行"
echo ""
echo "1. https://supabase.com/dashboard/project/vyddhllzjjpqxbouqivf/editor にアクセス"
echo "2. 「New Query」をクリック"
echo "3. 以下のファイルの内容をコピー＆ペースト:"
echo "   - supabase/migrations/007_fix_database_issues.sql"
echo "4. 「Run」をクリック"
echo ""