-- サンプル動画データの挿入
-- Note: 実際のYouTube動画URLを使用（教育目的）

INSERT INTO videos (
  id,
  title, 
  description, 
  url, 
  thumbnail_url, 
  duration, 
  category, 
  belt_level, 
  tags, 
  position,
  is_published,
  is_premium,
  created_at,
  updated_at
) VALUES
  (
    gen_random_uuid(),
    'クローズドガードの基本姿勢',
    'ブラジリアン柔術の基本ポジション、クローズドガードの正しい姿勢と相手のコントロール方法を学びます。',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    300,
    'fundamentals',
    'white',
    ARRAY['guard', 'basic', 'fundamentals', 'position'],
    'guard',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'アームドラッグからの展開',
    'クローズドガードからのアームドラッグの基本的な仕掛け方と、そこからのスイープやバックテイクへの展開。',
    'https://www.youtube.com/watch?v=9bZkp7q19f0',
    'https://img.youtube.com/vi/9bZkp7q19f0/maxresdefault.jpg',
    420,
    'technique',
    'blue',
    ARRAY['guard', 'armdrag', 'sweep', 'back-take'],
    'guard',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'シザースイープの基本',
    'ガードからの基本的なスイープ技術。タイミングと体重移動のポイントを解説。',
    'https://www.youtube.com/watch?v=PSRildGCw64',
    'https://img.youtube.com/vi/PSRildGCw64/maxresdefault.jpg',
    360,
    'sweep',
    'white',
    ARRAY['guard', 'sweep', 'basic', 'timing'],
    'guard',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'トライアングルチョークの仕掛け',
    'ガードポジションからの三角絞めの基本的な仕掛け方。手の使い方とレッグポジションがポイント。',
    'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    'https://img.youtube.com/vi/jNQXAC9IVRw/maxresdefault.jpg',
    480,
    'submission',
    'blue',
    ARRAY['guard', 'submission', 'choke', 'triangle'],
    'guard',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'サイドコントロール基礎',
    'サイドコントロールポジションの基本的な維持方法と相手の逃げを防ぐコツ。',
    'https://www.youtube.com/watch?v=Me-VhC9ieh0',
    'https://img.youtube.com/vi/Me-VhC9ieh0/maxresdefault.jpg',
    350,
    'position',
    'white',
    ARRAY['side-control', 'pressure', 'basic', 'control'],
    'side-control',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'マウントポジションからの攻撃',
    'マウントポジションを取った後の基本的な攻撃パターンとコントロール方法。',
    'https://www.youtube.com/watch?v=L_jWHffIx5E',
    'https://img.youtube.com/vi/L_jWHffIx5E/maxresdefault.jpg',
    390,
    'submission',
    'blue',
    ARRAY['mount', 'submission', 'control', 'attack'],
    'mount',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'エスケープの基本原理',
    'ボトムポジションからの基本的な脱出方法。フレーミングとヒップエスケープの重要性。',
    'https://www.youtube.com/watch?v=ZZ5LpwO-An4',
    'https://img.youtube.com/vi/ZZ5LpwO-An4/maxresdefault.jpg',
    420,
    'escape',
    'white',
    ARRAY['escape', 'defense', 'basic', 'framing'],
    'bottom',
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'パスガードの基礎',
    'ガードを突破するための基本的な戦略とテクニック。ポスチャーとプレッシャーのバランス。',
    'https://www.youtube.com/watch?v=LQCU36pkH7c',
    'https://img.youtube.com/vi/LQCU36pkH7c/maxresdefault.jpg',
    450,
    'guard-pass',
    'blue',
    ARRAY['guard-pass', 'pressure', 'strategy', 'posture'],
    'guard-pass',
    NOW(),
    NOW()
  );