// Database types for Murata BJJ
// This file should be auto-generated by Supabase CLI in production

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users_profile: {
        Row: {
          id: string
          user_id: string
          full_name: string | null
          belt_rank: 'white' | 'blue' | 'purple' | 'brown' | 'black' | null
          stripes: number
          weight_class: string | null
          preferred_position: string | null
          years_training: number
          dojo_id: string | null
          is_coach: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          full_name?: string | null
          belt_rank?: 'white' | 'blue' | 'purple' | 'brown' | 'black' | null
          stripes?: number
          weight_class?: string | null
          preferred_position?: string | null
          years_training?: number
          dojo_id?: string | null
          is_coach?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          full_name?: string | null
          belt_rank?: 'white' | 'blue' | 'purple' | 'brown' | 'black' | null
          stripes?: number
          weight_class?: string | null
          preferred_position?: string | null
          years_training?: number
          dojo_id?: string | null
          is_coach?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      techniques: {
        Row: {
          id: string
          name_ja: string
          name_en: string
          name_pt: string
          category: 'takedown' | 'guard' | 'pass' | 'submission' | 'escape' | 'transition'
          position: string
          difficulty: number
          description_ja: string | null
          description_en: string | null
          description_pt: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name_ja: string
          name_en: string
          name_pt: string
          category: 'takedown' | 'guard' | 'pass' | 'submission' | 'escape' | 'transition'
          position: string
          difficulty?: number
          description_ja?: string | null
          description_en?: string | null
          description_pt?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name_ja?: string
          name_en?: string
          name_pt?: string
          category?: 'takedown' | 'guard' | 'pass' | 'submission' | 'escape' | 'transition'
          position?: string
          difficulty?: number
          description_ja?: string | null
          description_en?: string | null
          description_pt?: string | null
          created_at?: string
        }
      }
      videos: {
        Row: {
          id: string
          title_ja: string
          title_en: string
          title_pt: string
          description_ja: string | null
          description_en: string | null
          description_pt: string | null
          url: string
          thumbnail_url: string | null
          duration: number | null
          technique_id: string | null
          instructor_id: string | null
          belt_requirement: string | null
          is_premium: boolean
          view_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title_ja: string
          title_en: string
          title_pt: string
          description_ja?: string | null
          description_en?: string | null
          description_pt?: string | null
          url: string
          thumbnail_url?: string | null
          duration?: number | null
          technique_id?: string | null
          instructor_id?: string | null
          belt_requirement?: string | null
          is_premium?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title_ja?: string
          title_en?: string
          title_pt?: string
          description_ja?: string | null
          description_en?: string | null
          description_pt?: string | null
          url?: string
          thumbnail_url?: string | null
          duration?: number | null
          technique_id?: string | null
          instructor_id?: string | null
          belt_requirement?: string | null
          is_premium?: boolean
          view_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      video_chapters: {
        Row: {
          id: string
          video_id: string
          title_ja: string
          title_en: string
          title_pt: string
          start_time: number
          end_time: number
          order_index: number
          created_at: string
        }
        Insert: {
          id?: string
          video_id: string
          title_ja: string
          title_en: string
          title_pt: string
          start_time: number
          end_time: number
          order_index: number
          created_at?: string
        }
        Update: {
          id?: string
          video_id?: string
          title_ja?: string
          title_en?: string
          title_pt?: string
          start_time?: number
          end_time?: number
          order_index?: number
          created_at?: string
        }
      }
      video_transcripts: {
        Row: {
          id: string
          video_id: string
          language: 'ja' | 'en' | 'pt'
          transcript: Json
          full_text: string | null
          created_at: string
        }
        Insert: {
          id?: string
          video_id: string
          language: 'ja' | 'en' | 'pt'
          transcript: Json
          full_text?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          video_id?: string
          language?: 'ja' | 'en' | 'pt'
          transcript?: Json
          full_text?: string | null
          created_at?: string
        }
      }
      user_progress: {
        Row: {
          id: string
          user_id: string
          technique_id: string
          progress_level: number
          last_practiced: string | null
          practice_count: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          technique_id: string
          progress_level?: number
          last_practiced?: string | null
          practice_count?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          technique_id?: string
          progress_level?: number
          last_practiced?: string | null
          practice_count?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      sparring_logs: {
        Row: {
          id: string
          user_id: string
          partner_name: string | null
          partner_belt: string | null
          duration: number | null
          starting_position: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          partner_name?: string | null
          partner_belt?: string | null
          duration?: number | null
          starting_position?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          partner_name?: string | null
          partner_belt?: string | null
          duration?: number | null
          starting_position?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      sparring_events: {
        Row: {
          id: string
          sparring_log_id: string
          event_type: 'pass' | 'sweep' | 'submission' | 'escape' | 'takedown' | 'back_take'
          technique_id: string | null
          success: boolean
          timestamp: number | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          sparring_log_id: string
          event_type: 'pass' | 'sweep' | 'submission' | 'escape' | 'takedown' | 'back_take'
          technique_id?: string | null
          success?: boolean
          timestamp?: number | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          sparring_log_id?: string
          event_type?: 'pass' | 'sweep' | 'submission' | 'escape' | 'takedown' | 'back_take'
          technique_id?: string | null
          success?: boolean
          timestamp?: number | null
          notes?: string | null
          created_at?: string
        }
      }
      flows: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          is_public: boolean
          tags: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          is_public?: boolean
          tags?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          is_public?: boolean
          tags?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      flow_nodes: {
        Row: {
          id: string
          flow_id: string
          technique_id: string | null
          custom_name: string | null
          position_x: number
          position_y: number
          node_type: string
          created_at: string
        }
        Insert: {
          id?: string
          flow_id: string
          technique_id?: string | null
          custom_name?: string | null
          position_x: number
          position_y: number
          node_type?: string
          created_at?: string
        }
        Update: {
          id?: string
          flow_id?: string
          technique_id?: string | null
          custom_name?: string | null
          position_x?: number
          position_y?: number
          node_type?: string
          created_at?: string
        }
      }
      flow_edges: {
        Row: {
          id: string
          flow_id: string
          source_node_id: string
          target_node_id: string
          label: string | null
          created_at: string
        }
        Insert: {
          id?: string
          flow_id: string
          source_node_id: string
          target_node_id: string
          label?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          flow_id?: string
          source_node_id?: string
          target_node_id?: string
          label?: string | null
          created_at?: string
        }
      }
      dojos: {
        Row: {
          id: string
          name: string
          description: string | null
          owner_id: string
          is_active: boolean
          max_members: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          owner_id: string
          is_active?: boolean
          max_members?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          owner_id?: string
          is_active?: boolean
          max_members?: number
          created_at?: string
          updated_at?: string
        }
      }
      dojo_members: {
        Row: {
          id: string
          dojo_id: string
          user_id: string
          role: 'owner' | 'coach' | 'student'
          joined_at: string
          invited_by: string | null
          invitation_token: string | null
          invitation_accepted_at: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          dojo_id: string
          user_id: string
          role: 'owner' | 'coach' | 'student'
          joined_at?: string
          invited_by?: string | null
          invitation_token?: string | null
          invitation_accepted_at?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          dojo_id?: string
          user_id?: string
          role?: 'owner' | 'coach' | 'student'
          joined_at?: string
          invited_by?: string | null
          invitation_token?: string | null
          invitation_accepted_at?: string | null
          is_active?: boolean
        }
      }
      curriculums: {
        Row: {
          id: string
          dojo_id: string
          title: string
          description: string | null
          belt_level: 'white' | 'blue' | 'purple' | 'brown' | 'black' | 'all' | null
          is_active: boolean
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          dojo_id: string
          title: string
          description?: string | null
          belt_level?: 'white' | 'blue' | 'purple' | 'brown' | 'black' | 'all' | null
          is_active?: boolean
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          dojo_id?: string
          title?: string
          description?: string | null
          belt_level?: 'white' | 'blue' | 'purple' | 'brown' | 'black' | 'all' | null
          is_active?: boolean
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      curriculum_items: {
        Row: {
          id: string
          curriculum_id: string
          item_type: 'video' | 'flow' | 'drill' | 'assessment'
          item_id: string | null
          title: string | null
          description: string | null
          order_index: number
          is_required: boolean
          created_at: string
        }
        Insert: {
          id?: string
          curriculum_id: string
          item_type: 'video' | 'flow' | 'drill' | 'assessment'
          item_id?: string | null
          title?: string | null
          description?: string | null
          order_index: number
          is_required?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          curriculum_id?: string
          item_type?: 'video' | 'flow' | 'drill' | 'assessment'
          item_id?: string | null
          title?: string | null
          description?: string | null
          order_index?: number
          is_required?: boolean
          created_at?: string
        }
      }
      assignments: {
        Row: {
          id: string
          dojo_id: string
          curriculum_id: string | null
          assigned_to: string
          assigned_by: string
          due_date: string | null
          status: 'pending' | 'in_progress' | 'completed' | 'overdue'
          completed_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          dojo_id: string
          curriculum_id?: string | null
          assigned_to: string
          assigned_by: string
          due_date?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'overdue'
          completed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          dojo_id?: string
          curriculum_id?: string | null
          assigned_to?: string
          assigned_by?: string
          due_date?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'overdue'
          completed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      assignment_progress: {
        Row: {
          id: string
          assignment_id: string
          curriculum_item_id: string
          completed_at: string | null
          score: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          assignment_id: string
          curriculum_item_id: string
          completed_at?: string | null
          score?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          assignment_id?: string
          curriculum_item_id?: string
          completed_at?: string | null
          score?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      dojo_content_visibility: {
        Row: {
          id: string
          dojo_id: string
          content_type: 'video' | 'flow'
          content_id: string
          is_private: boolean
          created_at: string
        }
        Insert: {
          id?: string
          dojo_id: string
          content_type: 'video' | 'flow'
          content_id: string
          is_private?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          dojo_id?: string
          content_type?: 'video' | 'flow'
          content_id?: string
          is_private?: boolean
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          plan_type: 'free' | 'pro' | 'dojo'
          status: 'active' | 'cancelled' | 'past_due' | 'trialing'
          current_period_start: string | null
          current_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          plan_type: 'free' | 'pro' | 'dojo'
          status: 'active' | 'cancelled' | 'past_due' | 'trialing'
          current_period_start?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          plan_type?: 'free' | 'pro' | 'dojo'
          status?: 'active' | 'cancelled' | 'past_due' | 'trialing'
          current_period_start?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      review_schedule: {
        Row: {
          id: string
          user_id: string
          technique_id: string
          next_review_date: string
          review_interval: number
          ease_factor: number
          review_count: number
          last_reviewed: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          technique_id: string
          next_review_date: string
          review_interval?: number
          ease_factor?: number
          review_count?: number
          last_reviewed?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          technique_id?: string
          next_review_date?: string
          review_interval?: number
          ease_factor?: number
          review_count?: number
          last_reviewed?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      has_active_subscription: {
        Args: {
          user_uuid: string
          required_plans: string[]
        }
        Returns: boolean
      }
      get_user_dojo_role: {
        Args: {
          user_uuid: string
          dojo_uuid: string
        }
        Returns: string
      }
      has_dojo_plan: {
        Args: {
          user_id: string
        }
        Returns: boolean
      }
      is_dojo_member: {
        Args: {
          user_id: string
          dojo_id: string
        }
        Returns: boolean
      }
      is_dojo_coach_or_owner: {
        Args: {
          user_id: string
          dojo_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}