#!/bin/bash

echo "🚀 Supabase CLIセットアップガイド"
echo "================================"
echo ""

# Check if Supabase CLI is installed
if command -v supabase &> /dev/null; then
    echo "✅ Supabase CLIはインストール済みです"
    echo "   Version: $(supabase --version)"
else
    echo "❌ Supabase CLIがインストールされていません"
    echo ""
    echo "📦 インストール方法:"
    echo ""
    echo "  macOS (Homebrew):"
    echo "  $ brew install supabase/tap/supabase"
    echo ""
    echo "  npm/yarn:"
    echo "  $ npm install -g supabase"
    echo ""
    echo "  その他のOS:"
    echo "  https://supabase.com/docs/guides/cli"
    echo ""
    exit 1
fi

echo ""
echo "📋 Supabase CLIでマイグレーションを実行する手順:"
echo ""
echo "1. Supabaseプロジェクトをリンク:"
echo "   $ supabase link --project-ref <your-project-ref>"
echo ""
echo "   Project Refは以下で確認できます:"
echo "   - Supabaseダッシュボード → Settings → General → Reference ID"
echo "   - URLの例: https://app.supabase.com/project/[ここがproject-ref]"
echo ""
echo "2. データベースのパスワードを入力:"
echo "   リンク時にデータベースパスワードの入力を求められます"
echo ""
echo "3. マイグレーションを実行:"
echo "   $ supabase db push"
echo ""
echo "   または特定のファイルを実行:"
echo "   $ supabase db push --file supabase/migrations/007_fix_database_issues.sql"
echo ""
echo "4. マイグレーション状態を確認:"
echo "   $ supabase db migrations list"
echo ""
echo "================================"
echo ""
echo "🔧 代替方法: psqlを使った直接実行"
echo ""
echo "1. DATABASE_URLを.env.localに追加:"
echo "   DATABASE_URL=\"postgresql://postgres:[password]@[host]:[port]/postgres\""
echo ""
echo "   接続情報は以下で確認:"
echo "   Supabaseダッシュボード → Settings → Database → Connection string"
echo ""
echo "2. psqlで実行:"
echo '   $ psql "$DATABASE_URL" -f supabase/migrations/007_fix_database_issues.sql'
echo ""
echo "================================"